FROM composer:

MAINTAINER wubaiqing <wubaiqing@vip.qq.com>

ENTRYPOINT ["composer config -g repo.packagist composer https://packagist.phpcomposer.com"]



$this->transion()

$this->commit()



@transion
public function getA() {

}